### ISSUE TITLE
JavaScript Parser

### ISSUE THREAD

**Issue by RussellAbraham** [qnxdev/bbstore#1]
Browser does not want to cache the javascript like this.

![03-audit](https://user-images.githubusercontent.com/35252806/83282882-1e5c9280-a18f-11ea-8c94-ba5babead246.PNG)
![02-x-javascript](https://user-images.githubusercontent.com/35252806/83282887-1ef52900-a18f-11ea-8ff5-b411b93ecc59.PNG)

This might just be an issue with the debuggers mime type specifications.

**Comment by qnxdev** [comment]
What tool is it?

Yeah I know I haven't added expiry, because the development haven't started yet. It's just a template made with create-react-app module. Have to start working soon‎.

Thanks for checking this out.

**Comment by RussellAbraham** [comment]
Blackberry 10 web inspector. Device settings / developer mode, and usb to another device or computer while browsing with the web inspector active. 

This tool is pretty nice if you need a javascript interpreter.
https://github.com/liriliri/eruda 

I connected all of its plugins to this CDN which caches it nicely. 
Also the platform scripts from blackberry10's seleniumCore are connected to this document and should load on the bb10 webkit browser.
https://s3-us-west-2.amazonaws.com/s.cdpn.io/1674766/eruda.html

**Comment by qnxdev** [comment]
Are you a BB10 user?
 Would you like to contribute?

**Comment by RussellAbraham** [comment]
Yes. What do you need?

From: Antony Tomy
Sent: Friday, May 29, 2020 10:01 AM
To: qnxdev/bbstore
Reply To: qnxdev/bbstore
Cc: Russell; Author
Subject: Re: [qnxdev/bbstore] JavaScript Parser (#1)


Are you a BB10 user?
Would you like to contribute?

**Comment by RussellAbraham** [comment]
Got a chance to build the repo, running on AWS cloud9. I think I can make it through these concepts but Ive never used protocol switch before.. 101

From: Antony Tomy
Sent: Friday, May 29, 2020 10:01 AM
To: qnxdev/bbstore
Reply To: qnxdev/bbstore
Cc: Russell; Author
Subject: Re: [qnxdev/bbstore] JavaScript Parser (#1)


Are you a BB10 user?
Would you like to contribute?

**Comment by RussellAbraham** [comment]
Got a chance to build the repo, running on AWS cloud9. I think I can make it through these concepts but Ive never used protocol switch before.. 101

That was interesting. I was over ethernet cable on my developement machine, aws doesnt let share a few things from its environment. I did run tests throught the whole thing and got quite a bit of data though. Ill try again later, maybe tomorrow.

AMD Backbone architecture I had in mind was very similar.Thanks I learned something here.

‎

**Comment by RussellAbraham** [comment]
Got a chance to build the repo, running on AWS cloud9. I think I can make it through these concepts but Ive never used protocol switch before.. 101

That was interesting. I was over ethernet cable on my developement machine, aws doesnt let share a few things from its environment. I did run tests throught the whole thing and got quite a bit of data though. I should have started a clean env from aws too, meta data is just all wrong. Ill try again later, maybe tomorrow.

AMD Backbone architecture I had in mind was very similar.Thanks I learned something here.

‎
‎
From: Antony Tomy
Sent: Friday, May 29, 2020 10:01 AM
To: qnxdev/bbstore
Reply To: qnxdev/bbstore
Cc: Russell; Author
Subject: Re: [qnxdev/bbstore] JavaScript Parser (#1)


Are you a BB10 user?
Would you like to contribute?

**Comment by qnxdev** [comment]
Okay, can we close this now?
