### ISSUE TITLE
public/download/ : .bar and .apk files vanished at commit 52ac8f0

### ISSUE THREAD

**Issue by karawitan** [qnxdev/bbstore#17]
Hi,

   I don't find the public/download/ directory in the repository.
Is it a volontary change ?

This commit removed the files, but nothing has been mentionned about this .

https://github.com/qnxdev/bbstore/commit/52ac8f0aaa217a0cdbf65397e34ba1118869df1b

Are the files stored in Firebase now ?
If this is so, It is a very exciting news !!

**Comment by qnxdev** [comment]
Yes files and icons are now in the firebase storage. You can Add/Update them from the site.

To add files, go to bbstore.now.sh/upload

To update a file, go to the bbstore.now.sh/apps ,  select the file to be updated, and click the edit button.

You can add/update games as well.

**Comment by qnxdev** [comment]
Thank you Oliver for pointing it out. I have added it back. The tools are still in that folder. But files and icons are now in the firebase storage. You can Add/Update them from the site.

To add files, go to bbstore.now.sh/upload

To update a file, go to the bbstore.now.sh/apps , select the file to be updated, and click the edit button.

You can add/update games as well.

**Comment by karawitan** [comment]
Great news about the upload form ! I'll let it know on out telegram channel. Thanks !
