### ISSUE TITLE
https://bb.sz7.me : can't connect to the server 

### ISSUE THREAD

**Issue by karawitan** [qnxdev/bbstore#18]
Hello,

  the url https://bb.sz7.me/ does not work at this time.
But url https://bbstore.vercel.app/ is still ok.

Should we update our bookmarks ?

**Comment by qnxdev** [comment]
The domain will be changing soon. sz7.me is not renewed. Kindly please use https://bbstore.vercel.app/

**Comment by karawitan** [comment]
okay thank you Sir !
