### ISSUE TITLE
bb.sz7.me : dns not found

### ISSUE THREAD

**Issue by karawitan** [qnxdev/bbstore#22]
Hi,

  just to let you know, this link is dead (see screenshot)
<img width="301" alt="Screenshot 2022-02-13 at 20 21 38" src="https://user-images.githubusercontent.com/37262984/153771149-3d5cc9cd-cb5d-4772-9125-92dd2f3dafa3.png">

Best Regards,

**Comment by qnxdev** [comment]
I didn't renew it since it expired
