### ISSUE TITLE
link to NightlyClock-1_82_0_5.bar: 404

### ISSUE THREAD

**Issue by karawitan** [qnxdev/bbstore#5]
https://bb.sz7.me/download/NightlyClock-1_82_0_5.bar

**Comment by qnxdev** [comment]
I have informed the author of commit.

@RussellAbraham 

https://github.com/qnxdev/bbstore/commit/d3432036cac60e197b7796e6b175f861a24418af#diff-b56eda1e8128878921a346773c31dc3d2a6fad13f733c8407ca17cee1c76cc70

**Comment by qnxdev** [comment]
Fixed
