### ISSUE TITLE
feeding bbstore from various channels ?

### ISSUE THREAD

**Issue by karawitan** [qnxdev/bbstore#7]
Hi !
 many thanks for accepting me to the project ! 
There are a few channels that are quite active at publishing bb10 ready apps
Maybe there would be some way to "pipe" some of their contributions to bbstore via a semi-automatic method ?

  here are the channel names for reference and further discussions:

https://docs.google.com/spreadsheets/u/0/d/1YtwpXvCpVXdxBhW-Bo9-5EJZU3GtXaHJFz6uduNXaBQ/htmlview#gid=0

https://web.telegram.org/#/im?p=@bb10barfiles
https://web.telegram.org/#/im?p=@BlackBerryOS10
https://web.telegram.org/#/im?p=@bb10dev

https://forums.crackberry.com/blackberry-10-apps-f274/filearchivehavens-unreleased-apps-bar-files-available-1138040

https://github.com/O-NX

2017
http://www.mediafire.com/?616hc1lhqkwgu

2013
http://www.blackberryos.com/playbook-games-apps/28608-list-working-playbook-bar-files.html

**Comment by qnxdev** [comment]
Can you explain about it? BBstore doesn't a backend yet. I haven't done it because I didn't feel like there was a need for it.

**Comment by qnxdev** [comment]
But you can always add apps into appdata.json

**Comment by karawitan** [comment]
The basic idea is to save some "human work", with a workflow that might look like:
- once an apk is published on selected channels,
- automatically check that this app already exist, 
- if yes, simply update version number and apk archive
- if not, find out the next available ID, then prepare a PR for human review

**Comment by qnxdev** [comment]
Will the bot do the work?

If yes, I will create an API using firestore so you can push appdata to firestore, and upload bar, apk to gcloud.

Ich bin busy till Dec 15th und we'll do the API afterwards.

**Comment by RussellAbraham** [comment]
> The basic idea is to save some "human work", with a workflow that might look like:
> 
> * once an apk is published on selected channels,
> * automatically check that this app already exist,
> * if yes, simply update version number and apk archive
> * if not, find out the next available ID, then prepare a PR for human review

Would this change the integrity of the files hashed value?

**Comment by karawitan** [comment]
Hi ! happy new year !
any progress about the API ?

**Comment by qnxdev** [comment]
I will do that using firebase but not very soon. You can try to do it as a branch if you are experienced with javascript

**Comment by qnxdev** [comment]
Added Firestore, Storage
