### ISSUE TITLE
submit new applications as PR via web form on bbstore

### ISSUE THREAD

**Issue by karawitan** [qnxdev/bbstore#8]
BBstore is a perfect project, that needs, IMHO very slight improvements to gather more audience:
Today, add an application to the store requires git, json, github knowledge.

Tomorrow, we would add an application in 2 steps:

Step 1
- Submit the application via a web form on bbstore
- this form is converted to gitag://pr-new-app-appname

Step 2
- PR review (-> human must take care of ID stuff here )
- merge pr-new-app-appname into master

...

What do you think ?

**Comment by qnxdev** [comment]
We will create a form to upload and Add data and a form to update apps

**Comment by qnxdev** [comment]
I will do that using firebase but not very soon

**Comment by qnxdev** [comment]
Added Firestore, Storage
